"""empty message

Revision ID: 1470b31c37
Revises: 3dce9f2e2c56
Create Date: 2014-09-28 12:11:02.801000

"""

# revision identifiers, used by Alembic.
revision = '1470b31c37'
down_revision = '3dce9f2e2c56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like_record', sa.Column('hash_code', sa.String(length=255), nullable=True))
    op.add_column('view_record', sa.Column('hash_code', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view_record', 'hash_code')
    op.drop_column('like_record', 'hash_code')
    ### end Alembic commands ###
