"""empty message

Revision ID: 179c728ce8b1
Revises: None
Create Date: 2014-09-11 22:35:05.762000

"""

# revision identifiers, used by Alembic.
revision = '179c728ce8b1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('humans', sa.Column('photo', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('humans', 'photo')
    ### end Alembic commands ###
