"""empty message

Revision ID: 242df53cef59
Revises: 179c728ce8b1
Create Date: 2014-09-18 20:47:04.476000

"""

# revision identifiers, used by Alembic.
revision = '242df53cef59'
down_revision = '179c728ce8b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
